name: .NET CD
on:
  push:
    tags:
    - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${VERSION} UrlSh.csproj
    - name: Publish
      run: dotnet publish --no-build --configuration Release --verbosity normal --output dist/ UrlSh.csproj
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: urlsh
        path: dist/**
        if-no-files-found: error
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: 'read'
      packages: 'write'
    env:
      REGISTRY: ghcr.io
      REPO_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: urlsh
          path: dist/
      - name: Set output
        id: vars
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to ghcr
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: dist/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ steps.vars.outputs.tag }}
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
